### ISSUE TITLE
Subdomain issue

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Pinger-WRIO-App#425]
Комментарии отображаются с сабдоменов, см. комментарии в https://wrioos.com
виден комментарий от 
titter.wrioos.com
чтобы решить проблему нужно попробовать добавить https:// в ссылку в твитах.

**Comment by AlexeyAnshakov** [comment]
Михаил, это уже фиксилось?

**Comment by michbil** [comment]
по-моему да, сейчас урл вместе с протоколом отображается. Возможно там старые твиты видны?
