### ISSUE TITLE
Counting characters

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Pinger-WRIO-App#463]
https://twitter.com/alexey_anshakov/status/862668097928531968
If you press Enter, e.x. do a line break with a long text, you get a bug.
Here is an example with Enter pressed two times
https://twitter.com/alexey_anshakov/status/862669211365253120

**Comment by AlexeyAnshakov** [comment]
At the moment let's do a quick fix and forbid a new line with Enter.

**Comment by spirinvladimir** [comment]
Done.
