### ISSUE TITLE
Creating a list using the first comment

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Pinger-WRIO-App#496]
В связи с тем, что большинство страниц сейчас (и в будущем) будут без комментариев, то нет необходимости создавать пустые списки в твиттере, что особенно важно в связи с ограничением на  количество виджетов.

В случае выбора в редакторе "Save as" нужно автоматически снимать галочку "enable comments" и делать disabled, т.к. мы не знаем для какого URL создавать виджет комментариев из-за отсутствия информации о том, по какой ссылке будет размещена страница.

В ином случае при включении галочки "enable comments" еще не создавать виджет, а только сохранять в JSON-LD
>"comment": "875721502196465664"

Это ID виджета, который привязан к фиктивной странице и никогда не будет содержать комментарии, а значит подходит для отображения пустого списка и на этапе отсутствия комментариев идентичен реальному списку. ID будет играть роль маркера, по которому мы будем определять, что комментарии включены автором, но их пока нет.

После отправки первого комментария нужно создавать новый виджет для данного URL, сохранять в JSON-LD полученный ID вместо "875721502196465664" и перегружать виджет Титтера.

**Comment by michbil** [comment]
@AlexeyAnshakov будет сложность в плане юзабилити, т.к. первый комментарий появится через минуту а то и более после первого комментария. По хорошему неплохо было бы рисовать виртуальный таймлайн с только что оправленным сообщением, до тех пор пока не будет создан поисковый виджет.

**Comment by AlexeyAnshakov** [comment]
Пользователи находят Core и создают страницы, хотя мы пока не рекламируем функционал. Владимир, сколько ориентировочно времени уйдет чтобы пока сделать для страниц с включенными, но без единого комментария отображение твитленты-заглушки и создание виджета лишь после первого комментария?

**Comment by spirinvladimir** [comment]
Созданная страница может быть трех типов относительно значения/наличия поля comment в JSON-LD:

1. Отсутствие поля comment в JSON-LD для страниц с выключенными комментариями (enable comments -> disabled) либо для страниц созданных через "Save as".
2. Значение поля comment "875721502196465664" для страниц без комментариев.
3. Значение поля comment из widget ID по созданному виджету.

Каждый пункт можно реализовывать отдельно как подзадачу. На каждый пункт можно заложить по часу времени.

**Comment by spirinvladimir** [comment]
Завершено. Можно закрывать.
