### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Pinger-WRIO-App#518]
- при нажатии на "What are Credit coins?" в виджете создания комментария нажимается и кнопка "Get free Credit coins". Если не займет время, то хорошо бы сделать обновление баланса без необходимости перегружать страницу.
- после нажатия надо выводить "Wait x minutes", но без значка loading
- мы можем выбрать png или gif формат для сохранения картинки-коммента? Для четкости текста, а также меньшего размера
- можно либо отправлять длинный комментарий либо картинку. После начала ввода текста, кнопка "photo" должна заменять на "Clear text area and add photo". В случае добавления фотографии, вместо text area отображать 
```
<div class="well"><h4>Success!</h4><p>The photo has been uploaded</p></div>
```
А кнопку заменять на "Delete photo and add text". Больше https://github.com/webRunes/Pinger-WRIO-App/issues/39

**Comment by spirinvladimir** [comment]
Done

**Comment by AlexeyAnshakov** [comment]
>при нажатии на "What are Credit coins?" в виджете создания комментария нажимается и кнопка "Get free Credit coins".

по прежнему есть проблема.

**Comment by spirinvladimir** [comment]
Возможность загрузки jpg возвращена.

**Comment by spirinvladimir** [comment]
сделал конпокой _Clear text area and add photo_ [PR](https://github.com/webRunes/WRIO-InternetOS/pull/1395)

**Comment by spirinvladimir** [comment]
Removed action from link "What are Credit coins?".

**Comment by spirinvladimir** [comment]
Done.
